---
language: python
python:
  - "2.7"

# Install python packages for ansible and linters.
# Install a minimal TexLive installation for LaTeX support.
install:
  - "pip install -r requirements.txt"
  - "apt-get install texlive-latex-recommended -y"

# Execute linting tests before running the main playbook.
# If any of these tasks fail, the entire build fails immediately.
# Also must specify the location of the ansible.cfg file as it is
# not in the role's top directory for cleanliness. Last, must
# ensure pdflatex will write output files where needed, basically
# disabling the paranoid behavior about output files.
before_script:
  - "./tests/lint.sh"
  - "export ANSIBLE_CONFIG=tests/ansible.cfg"
  - "export openout_any=a"

# Run the role playbook with mock inputs to validate the role functionality.
# Mock inputs are stored as 'control' group variables in the inventory.yml file.
script:
  - "ansible-playbook tests/test_playbook.yml -i tests/inventory.yml"
...
