---
language: python
python:
  - "2.7"
  - "3.6"

# Install python packages for ansible and linters.
# Install a minimal TexLive installation for LaTeX support.
install:
  - "make setup"

# Execute linting tests before running the main playbook.
# If any of these tasks fail, the entire build fails immediately.
# Also must specify the location of the ansible.cfg file as it is
# not in the role's top directory for cleanliness. Last, must
# ensure pdflatex will write output files where needed, basically
# disabling the paranoid behavior about output files.
before_script:
  - "make lint"

# Run the role playbook with mock inputs to validate the role functionality.
# Mock inputs are stored as 'control' group variables in the inv.yml file.
script:
  - "export ANSIBLE_CONFIG=tests/ansible.cfg"
  - "export openout_any=a"
  - "make test"
...
