---
# The 'archive' module can delete files that it includes, but not
# directories. This explicit task, iterates over the entity list
# and deletes all entity-specific file directories. The directories
# being removed have the following format:
#   "/etc/ansible/(playbook)/files/(id)_(dtg)"
- name: "SYS >> Clean up empty config directories"
  listen: "archive_handler"
  file:
    path: "{{ PBF }}{{ item.id }}_{{ DTG }}"
    state: "absent"
  loop: "{{ entity_list }}"
  loop_control:
    label: "{{ PBF }}{{ item.id }}_{{ DTG }}"

# The infrastructure directory only exists once per templater run,
# not per entity, so there is only one to remove.
#   "/etc/ansible/(playbook)/files/infra_(dtg)"
- name: "SYS >> Clean up empty infra directory"
  listen: "archive_handler"
  file:
    path: "{{ PBFI }}"
    state: "absent"

# Users can optionally copy the ZIP bundle to a SCP server by copying
# the SCP command written to stdout for simplicity.
- name: "SYS >> Copy the command below to SCP the archive off-box"
  listen: "archive_handler"
  debug:
    msg: >-
      scp {{ PBA }}{{ zip_name }}_{{ DTG }}.zip
      {{ scp.user }}@{{ scp.host }}:/mkfd/
...
